# Generated by Django 4.0.6 on 2022-08-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumXml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('release_year', models.DateField()),
                ('author', models.CharField(max_length=40)),
                ('best_song', models.CharField(max_length=40)),
                ('xml', models.FileField(upload_to='media/albums')),
            ],
        ),
    ]
